  
dist: trusty
language: java
jdk:
 - oraclejdk13

addons:
 sonarcloud:
  organization: "fra199889"
  token:
   secure: "0204bda13c7b36b7f0f39f64b3285eb6ad49b72a"

script: 

- ant build
- sonar-scanner



















